/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.Arrays;
import javax.swing.JLabel;

/**
 *
 * @author PC PERSONAL
 */
public class buscarPrestamos_c extends javax.swing.JFrame {
    
    public String[] deudores_resibidos;   
    public JLabel etiNombreDeu, etiNombrePres, etiNumCuotas, etiCuotaActual, etiValorCuo, etiDireccion;
    public String valorCuota,numCuotas, cuotaActual, prestamista, deudor, direccion; //variables sin asignar
    
    /**
     * Creates new form buscarPrestamos
     */
    public buscarPrestamos_c(JLabel nombPres, JLabel numCuotas, JLabel cuotaAct, JLabel valorCuo, JLabel direcc, JLabel nombreDeudor, String[] Deurs) {
        initComponents();
        setLocation(100, 100);
        etiNombrePres = nombPres;
        etiNombreDeu = nombreDeudor;
        etiNumCuotas = numCuotas;
        etiCuotaActual = cuotaAct;
        etiValorCuo = valorCuo;
        etiDireccion = direcc;
        deudores_resibidos = Deurs;
    }
    public buscarPrestamos_c(){
        initComponents();
        setLocation(100, 100);
    }
    
    void asignarDescripcion(){
        //Asignar los valores a las etiquetas        
        etiNombrePres.setText(" Nombre del prestamista: \t----");
        etiNumCuotas.setText(" Total de cuotas: \t----");
        etiCuotaActual.setText(" Cuota Nro --");
        etiValorCuo.setText(" Valor de la cuota: \t----");
        etiDireccion.setText(" Dirreccion: \t----");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barraPrestamos = new javax.swing.JPanel();
        panelPrestamos = new javax.swing.JPanel();
        etiPrestamos = new javax.swing.JLabel();
        cobrador_prestamo1 = new javax.swing.JPanel();
        etiPrestamo_c1 = new javax.swing.JLabel();
        cobrador_prestamo2 = new javax.swing.JPanel();
        etiPrestamo_c2 = new javax.swing.JLabel();
        cobrador_prestamo3 = new javax.swing.JPanel();
        etiPrestamo_c3 = new javax.swing.JLabel();
        cobrador_prestamo4 = new javax.swing.JPanel();
        etiPrestamo_c4 = new javax.swing.JLabel();
        cobrador_prestamo5 = new javax.swing.JPanel();
        etiPrestamo_c5 = new javax.swing.JLabel();
        cobrador_prestamo6 = new javax.swing.JPanel();
        etiPrestamo_c6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(98, 111, 71));

        barraPrestamos.setBackground(new java.awt.Color(254, 250, 224));

        panelPrestamos.setBackground(new java.awt.Color(164, 180, 101));

        etiPrestamos.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        etiPrestamos.setForeground(new java.awt.Color(254, 250, 224));
        etiPrestamos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPrestamos.setText("PRESTAMOS");

        javax.swing.GroupLayout panelPrestamosLayout = new javax.swing.GroupLayout(panelPrestamos);
        panelPrestamos.setLayout(panelPrestamosLayout);
        panelPrestamosLayout.setHorizontalGroup(
            panelPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelPrestamosLayout.setVerticalGroup(
            panelPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        cobrador_prestamo1.setBackground(new java.awt.Color(255, 207, 80));

        etiPrestamo_c1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        etiPrestamo_c1.setForeground(new java.awt.Color(98, 111, 71));
        etiPrestamo_c1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPrestamo_c1.setText("Prestamo 1");
        etiPrestamo_c1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        etiPrestamo_c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiPrestamo_c1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cobrador_prestamo1Layout = new javax.swing.GroupLayout(cobrador_prestamo1);
        cobrador_prestamo1.setLayout(cobrador_prestamo1Layout);
        cobrador_prestamo1Layout.setHorizontalGroup(
            cobrador_prestamo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cobrador_prestamo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamo_c1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );
        cobrador_prestamo1Layout.setVerticalGroup(
            cobrador_prestamo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cobrador_prestamo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamo_c1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        cobrador_prestamo2.setBackground(new java.awt.Color(255, 207, 80));

        etiPrestamo_c2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        etiPrestamo_c2.setForeground(new java.awt.Color(98, 111, 71));
        etiPrestamo_c2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPrestamo_c2.setText("Prestamo 2");
        etiPrestamo_c2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        etiPrestamo_c2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiPrestamo_c2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cobrador_prestamo2Layout = new javax.swing.GroupLayout(cobrador_prestamo2);
        cobrador_prestamo2.setLayout(cobrador_prestamo2Layout);
        cobrador_prestamo2Layout.setHorizontalGroup(
            cobrador_prestamo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cobrador_prestamo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamo_c2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );
        cobrador_prestamo2Layout.setVerticalGroup(
            cobrador_prestamo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cobrador_prestamo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamo_c2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        cobrador_prestamo3.setBackground(new java.awt.Color(255, 207, 80));

        etiPrestamo_c3.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        etiPrestamo_c3.setForeground(new java.awt.Color(98, 111, 71));
        etiPrestamo_c3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPrestamo_c3.setText("Prestamo 3");
        etiPrestamo_c3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        etiPrestamo_c3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiPrestamo_c3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cobrador_prestamo3Layout = new javax.swing.GroupLayout(cobrador_prestamo3);
        cobrador_prestamo3.setLayout(cobrador_prestamo3Layout);
        cobrador_prestamo3Layout.setHorizontalGroup(
            cobrador_prestamo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cobrador_prestamo3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamo_c3, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );
        cobrador_prestamo3Layout.setVerticalGroup(
            cobrador_prestamo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cobrador_prestamo3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamo_c3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        cobrador_prestamo4.setBackground(new java.awt.Color(255, 207, 80));

        etiPrestamo_c4.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        etiPrestamo_c4.setForeground(new java.awt.Color(98, 111, 71));
        etiPrestamo_c4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPrestamo_c4.setText("Prestamo 4");
        etiPrestamo_c4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        etiPrestamo_c4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiPrestamo_c4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cobrador_prestamo4Layout = new javax.swing.GroupLayout(cobrador_prestamo4);
        cobrador_prestamo4.setLayout(cobrador_prestamo4Layout);
        cobrador_prestamo4Layout.setHorizontalGroup(
            cobrador_prestamo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cobrador_prestamo4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamo_c4, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );
        cobrador_prestamo4Layout.setVerticalGroup(
            cobrador_prestamo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cobrador_prestamo4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamo_c4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        cobrador_prestamo5.setBackground(new java.awt.Color(255, 207, 80));

        etiPrestamo_c5.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        etiPrestamo_c5.setForeground(new java.awt.Color(98, 111, 71));
        etiPrestamo_c5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPrestamo_c5.setText("Prestamo 5");
        etiPrestamo_c5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        etiPrestamo_c5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiPrestamo_c5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cobrador_prestamo5Layout = new javax.swing.GroupLayout(cobrador_prestamo5);
        cobrador_prestamo5.setLayout(cobrador_prestamo5Layout);
        cobrador_prestamo5Layout.setHorizontalGroup(
            cobrador_prestamo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cobrador_prestamo5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamo_c5, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );
        cobrador_prestamo5Layout.setVerticalGroup(
            cobrador_prestamo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cobrador_prestamo5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamo_c5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        cobrador_prestamo6.setBackground(new java.awt.Color(255, 207, 80));

        etiPrestamo_c6.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        etiPrestamo_c6.setForeground(new java.awt.Color(98, 111, 71));
        etiPrestamo_c6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPrestamo_c6.setText("Prestamo 6");
        etiPrestamo_c6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        etiPrestamo_c6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiPrestamo_c6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cobrador_prestamo6Layout = new javax.swing.GroupLayout(cobrador_prestamo6);
        cobrador_prestamo6.setLayout(cobrador_prestamo6Layout);
        cobrador_prestamo6Layout.setHorizontalGroup(
            cobrador_prestamo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cobrador_prestamo6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamo_c6, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );
        cobrador_prestamo6Layout.setVerticalGroup(
            cobrador_prestamo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cobrador_prestamo6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamo_c6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout barraPrestamosLayout = new javax.swing.GroupLayout(barraPrestamos);
        barraPrestamos.setLayout(barraPrestamosLayout);
        barraPrestamosLayout.setHorizontalGroup(
            barraPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barraPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(barraPrestamosLayout.createSequentialGroup()
                        .addGroup(barraPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cobrador_prestamo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cobrador_prestamo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(barraPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(barraPrestamosLayout.createSequentialGroup()
                                .addComponent(cobrador_prestamo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cobrador_prestamo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(barraPrestamosLayout.createSequentialGroup()
                                .addComponent(cobrador_prestamo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cobrador_prestamo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        barraPrestamosLayout.setVerticalGroup(
            barraPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(barraPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cobrador_prestamo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cobrador_prestamo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cobrador_prestamo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(barraPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cobrador_prestamo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cobrador_prestamo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cobrador_prestamo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barraPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barraPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etiPrestamo_c1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiPrestamo_c1MouseClicked
        // TODO add your handling code here:
        etiNombreDeu.setText(deudores_resibidos[0]);
        asignarDescripcion();
        dispose();
    }//GEN-LAST:event_etiPrestamo_c1MouseClicked

    private void etiPrestamo_c2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiPrestamo_c2MouseClicked
        // TODO add your handling code here:
        etiNombreDeu.setText(deudores_resibidos[1]);
        dispose();
    }//GEN-LAST:event_etiPrestamo_c2MouseClicked

    private void etiPrestamo_c3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiPrestamo_c3MouseClicked
        // TODO add your handling code here:
        etiNombreDeu.setText(deudores_resibidos[2]);
        asignarDescripcion();
        dispose();
    }//GEN-LAST:event_etiPrestamo_c3MouseClicked

    private void etiPrestamo_c4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiPrestamo_c4MouseClicked
        // TODO add your handling code here:
        etiNombreDeu.setText(deudores_resibidos[3]);
        asignarDescripcion();
        dispose();
    }//GEN-LAST:event_etiPrestamo_c4MouseClicked

    private void etiPrestamo_c5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiPrestamo_c5MouseClicked
        // TODO add your handling code here:
        etiNombreDeu.setText(deudores_resibidos[4]);
        asignarDescripcion();
        dispose();
    }//GEN-LAST:event_etiPrestamo_c5MouseClicked

    private void etiPrestamo_c6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiPrestamo_c6MouseClicked
        // TODO add your handling code here
        etiNombreDeu.setText(deudores_resibidos[5]);
        asignarDescripcion();
        dispose();
    }//GEN-LAST:event_etiPrestamo_c6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buscarPrestamos_c.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buscarPrestamos_c.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buscarPrestamos_c.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buscarPrestamos_c.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buscarPrestamos_c().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraPrestamos;
    private javax.swing.JPanel cobrador_prestamo1;
    private javax.swing.JPanel cobrador_prestamo2;
    private javax.swing.JPanel cobrador_prestamo3;
    private javax.swing.JPanel cobrador_prestamo4;
    private javax.swing.JPanel cobrador_prestamo5;
    private javax.swing.JPanel cobrador_prestamo6;
    private javax.swing.JLabel etiPrestamo_c1;
    private javax.swing.JLabel etiPrestamo_c2;
    private javax.swing.JLabel etiPrestamo_c3;
    private javax.swing.JLabel etiPrestamo_c4;
    private javax.swing.JLabel etiPrestamo_c5;
    private javax.swing.JLabel etiPrestamo_c6;
    private javax.swing.JLabel etiPrestamos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelPrestamos;
    // End of variables declaration//GEN-END:variables
}
