/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author conta
 */

public class Cobrador extends javax.swing.JFrame {
    
    String Deudores[] = {"DEUDOR 1","DEUDOR 2","DEUDOR 3","DEUDOR 4","DEUDOR 5","DEUDOR 6"};
    /**
     * Creates new form Cobrador
     */
    public Cobrador(String CobradorName) {
        initComponents();
        setLocationRelativeTo(null);
        etiNombreCobrador.setText(CobradorName);
    }

    public Cobrador(){
        initComponents();
        setLocationRelativeTo(null);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        bkgHeader = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        etiTituloCobrador = new javax.swing.JLabel();
        imgUsuario = new javax.swing.JLabel();
        panelVolver = new javax.swing.JPanel();
        imgVolver = new javax.swing.JLabel();
        bkgCuerpo = new javax.swing.JPanel();
        panelBackgroundDescripcion = new javax.swing.JPanel();
        etiNombreDeuAsig = new javax.swing.JLabel();
        panelDescripcion = new javax.swing.JPanel();
        etiTutuloDescripcion = new javax.swing.JLabel();
        etiNombrePrestamista = new javax.swing.JLabel();
        etiCuotaActual = new javax.swing.JLabel();
        etiNumeroCueotas = new javax.swing.JLabel();
        etiDireccion = new javax.swing.JLabel();
        etiValorCuota = new javax.swing.JLabel();
        panelTotalPrestamo = new javax.swing.JPanel();
        etiValorTotalPrestamo = new javax.swing.JLabel();
        etiTotalDeprestamo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        etiNombreCobrador = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBuscar_c = new javax.swing.JMenu();
        menuItemBuscarPrestamos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(164, 180, 101));

        bkgHeader.setBackground(new java.awt.Color(254, 250, 224));

        panelTitulo.setBackground(new java.awt.Color(255, 207, 80));

        etiTituloCobrador.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N
        etiTituloCobrador.setForeground(new java.awt.Color(98, 111, 71));
        etiTituloCobrador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiTituloCobrador.setText("Cobrador");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiTituloCobrador, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiTituloCobrador, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        imgUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario x100.png"))); // NOI18N

        panelVolver.setBackground(new java.awt.Color(255, 207, 80));

        imgVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver x24.png"))); // NOI18N
        imgVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgVolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelVolverLayout = new javax.swing.GroupLayout(panelVolver);
        panelVolver.setLayout(panelVolverLayout);
        panelVolverLayout.setHorizontalGroup(
            panelVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVolverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(imgVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelVolverLayout.setVerticalGroup(
            panelVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVolverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(imgVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout bkgHeaderLayout = new javax.swing.GroupLayout(bkgHeader);
        bkgHeader.setLayout(bkgHeaderLayout);
        bkgHeaderLayout.setHorizontalGroup(
            bkgHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkgHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        bkgHeaderLayout.setVerticalGroup(
            bkgHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkgHeaderLayout.createSequentialGroup()
                .addGroup(bkgHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bkgHeaderLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bkgHeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(bkgHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bkgCuerpo.setBackground(new java.awt.Color(98, 111, 71));

        panelBackgroundDescripcion.setBackground(new java.awt.Color(254, 250, 224));

        etiNombreDeuAsig.setForeground(new java.awt.Color(98, 111, 71));
        etiNombreDeuAsig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiNombreDeuAsig.setText("Nombre del deudor");
        etiNombreDeuAsig.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(98, 111, 71), 3));

        panelDescripcion.setBackground(new java.awt.Color(254, 250, 224));
        panelDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(98, 111, 71), 3));

        etiTutuloDescripcion.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        etiTutuloDescripcion.setForeground(new java.awt.Color(98, 111, 71));
        etiTutuloDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiTutuloDescripcion.setText("DESCRIPCION");

        etiNombrePrestamista.setForeground(new java.awt.Color(98, 111, 71));
        etiNombrePrestamista.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiNombrePrestamista.setText(" Nombre del prestamista: ");

        etiCuotaActual.setForeground(new java.awt.Color(98, 111, 71));
        etiCuotaActual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiCuotaActual.setText(" Cuota Nro ");

        etiNumeroCueotas.setForeground(new java.awt.Color(98, 111, 71));
        etiNumeroCueotas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiNumeroCueotas.setText(" Numero de cuotas: ");

        etiDireccion.setForeground(new java.awt.Color(98, 111, 71));
        etiDireccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiDireccion.setText(" Direccion: ");

        etiValorCuota.setForeground(new java.awt.Color(98, 111, 71));
        etiValorCuota.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiValorCuota.setText(" Valor de la cuota: ");

        javax.swing.GroupLayout panelDescripcionLayout = new javax.swing.GroupLayout(panelDescripcion);
        panelDescripcion.setLayout(panelDescripcionLayout);
        panelDescripcionLayout.setHorizontalGroup(
            panelDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDescripcionLayout.createSequentialGroup()
                        .addComponent(etiTutuloDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(etiNombrePrestamista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiCuotaActual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiNumeroCueotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiValorCuota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelDescripcionLayout.setVerticalGroup(
            panelDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiTutuloDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiNombrePrestamista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiNumeroCueotas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiCuotaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiValorCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        panelTotalPrestamo.setBackground(new java.awt.Color(164, 180, 101));

        etiValorTotalPrestamo.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        etiValorTotalPrestamo.setForeground(new java.awt.Color(98, 111, 71));
        etiValorTotalPrestamo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiValorTotalPrestamo.setText("1.000.000");

        javax.swing.GroupLayout panelTotalPrestamoLayout = new javax.swing.GroupLayout(panelTotalPrestamo);
        panelTotalPrestamo.setLayout(panelTotalPrestamoLayout);
        panelTotalPrestamoLayout.setHorizontalGroup(
            panelTotalPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiValorTotalPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTotalPrestamoLayout.setVerticalGroup(
            panelTotalPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiValorTotalPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        etiTotalDeprestamo.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 10)); // NOI18N
        etiTotalDeprestamo.setForeground(new java.awt.Color(98, 111, 71));
        etiTotalDeprestamo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiTotalDeprestamo.setText("Total de prestamo");

        jPanel1.setBackground(new java.awt.Color(164, 180, 101));

        etiNombreCobrador.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        etiNombreCobrador.setForeground(new java.awt.Color(98, 111, 71));
        etiNombreCobrador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiNombreCobrador.setText("Nombre del Cobrador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiNombreCobrador, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiNombreCobrador, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelBackgroundDescripcionLayout = new javax.swing.GroupLayout(panelBackgroundDescripcion);
        panelBackgroundDescripcion.setLayout(panelBackgroundDescripcionLayout);
        panelBackgroundDescripcionLayout.setHorizontalGroup(
            panelBackgroundDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundDescripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBackgroundDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBackgroundDescripcionLayout.createSequentialGroup()
                        .addComponent(etiNombreDeuAsig, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(panelBackgroundDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiTotalDeprestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTotalPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        panelBackgroundDescripcionLayout.setVerticalGroup(
            panelBackgroundDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundDescripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBackgroundDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBackgroundDescripcionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(etiTotalDeprestamo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTotalPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBackgroundDescripcionLayout.createSequentialGroup()
                        .addGroup(panelBackgroundDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(etiNombreDeuAsig, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout bkgCuerpoLayout = new javax.swing.GroupLayout(bkgCuerpo);
        bkgCuerpo.setLayout(bkgCuerpoLayout);
        bkgCuerpoLayout.setHorizontalGroup(
            bkgCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkgCuerpoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panelBackgroundDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bkgCuerpoLayout.setVerticalGroup(
            bkgCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkgCuerpoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panelBackgroundDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bkgCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bkgHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bkgHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bkgCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuBuscar_c.setText("Buscar");

        menuItemBuscarPrestamos.setText("Prestamos");
        menuItemBuscarPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemBuscarPrestamosMouseClicked(evt);
            }
        });
        menuBuscar_c.add(menuItemBuscarPrestamos);

        jMenuBar1.add(menuBuscar_c);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgVolverMouseClicked
        Login abrir = new Login();
        abrir.setVisible(true);
        dispose();
    }//GEN-LAST:event_imgVolverMouseClicked

    private void menuItemBuscarPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemBuscarPrestamosMouseClicked
        // TODO add your handling code here:
        buscarPrestamos_c abrBuscarPrest = new buscarPrestamos_c(etiNombrePrestamista, etiNumeroCueotas, etiCuotaActual, etiValorCuota, etiDireccion, etiNombreDeuAsig, Deudores);
        abrBuscarPrest.setVisible(true);
    }//GEN-LAST:event_menuItemBuscarPrestamosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(Cobrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(Cobrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(Cobrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Cobrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new Cobrador().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel bkgCuerpo;
    private javax.swing.JPanel bkgHeader;
    private javax.swing.JLabel etiCuotaActual;
    private javax.swing.JLabel etiDireccion;
    private javax.swing.JLabel etiNombreCobrador;
    private javax.swing.JLabel etiNombreDeuAsig;
    private javax.swing.JLabel etiNombrePrestamista;
    private javax.swing.JLabel etiNumeroCueotas;
    private javax.swing.JLabel etiTituloCobrador;
    private javax.swing.JLabel etiTotalDeprestamo;
    private javax.swing.JLabel etiTutuloDescripcion;
    private javax.swing.JLabel etiValorCuota;
    private javax.swing.JLabel etiValorTotalPrestamo;
    private javax.swing.JLabel imgUsuario;
    private javax.swing.JLabel imgVolver;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuBuscar_c;
    private javax.swing.JMenu menuItemBuscarPrestamos;
    private javax.swing.JPanel panelBackgroundDescripcion;
    private javax.swing.JPanel panelDescripcion;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelTotalPrestamo;
    private javax.swing.JPanel panelVolver;
    // End of variables declaration//GEN-END:variables
}
