/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Handlers.CobradorHandler;
import com.toedter.calendar.JDateChooser;
import java.awt.Image;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Boris
 */
public class crearUsuario extends javax.swing.JFrame {

    private Map<String, String> descripcionesRoles;
    // Mapa para almacenar las rutas de las imágenes de cada rol
    private Map<String, String> imagenesRoles;

    public crearUsuario() {
        initComponents();
        inicializarDatosRoles();
        configurarEventos();
    }

    private void inicializarDatosRoles() {
        descripcionesRoles = new HashMap<>();
        imagenesRoles = new HashMap<>();

        // Agregar descripciones e imágenes para cada rol
        descripcionesRoles.put("Quiero prestar", "Este rol tiene acceso completo al sistema.\nPuede gestionar usuarios, configuraciones y todos los módulos.");
        descripcionesRoles.put("Quiero cobrar", "Rol para profesores.\nPuede gestionar cursos, calificaciones y asistencia de estudiantes.");
        descripcionesRoles.put("Quiero que me presten", "Rol para alumnos.\nPuede ver sus cursos, calificaciones y material de estudio.");
        descripcionesRoles.put("Roles", "Descripcion de roles.\nSeleccione un rol para ver su descripcion.");

        // Rutas de las imágenes (ajusta según tu estructura de proyecto)
        imagenesRoles.put("Quiero prestar", "/img/admin.png");
        imagenesRoles.put("Quiero cobrar", "/imagenes/teacher.png");
        imagenesRoles.put("Quiero que me presten", "/imagenes/student.png");
        imagenesRoles.put("Roles", "/imagenes/guest.png");
    }

    private void configurarEventos() {
        rolesBox.addActionListener(e -> {
            cargarDescripcionEImagen();
        });
    }

    private void cargarDescripcionEImagen() {
        String rolSeleccionado = (String) rolesBox.getSelectedItem();

        if (rolSeleccionado != null) {
            // Cargar descripción
            String descripcion = descripcionesRoles.get(rolSeleccionado);
            descripcionArea.setText(descripcion != null ? descripcion : "Descripción no disponible");

            // Cargar imagen
            String rutaImagen = imagenesRoles.get(rolSeleccionado);
            if (rutaImagen != null) {
                try {
                    ImageIcon icon = new ImageIcon(getClass().getResource(rutaImagen));
                    // Escalar la imagen si es necesario
                    Image imagen = icon.getImage().getScaledInstance(
                            imagenRol.getWidth(),
                            imagenRol.getHeight(),
                            Image.SCALE_SMOOTH);
                    imagenRol.setIcon(new ImageIcon(imagen));
                } catch (Exception e) {
                    imagenRol.setIcon(null);
                    imagenRol.setText("Imagen no encontrada");
                }
            } else {
                imagenRol.setIcon(null);
                imagenRol.setText("Imagen no disponible");
            }
        }
    }

    // Método generado por NetBeans para inicializar componentes
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        Background = new javax.swing.JPanel();
        bkgHeader = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        etiTituloPrestamista = new javax.swing.JLabel();
        panelVolver = new javax.swing.JPanel();
        imgVolver = new javax.swing.JLabel();
        nombre_field = new javax.swing.JTextField();
        apellido_field = new javax.swing.JTextField();
        documento_field = new javax.swing.JTextField();
        direccion_field = new javax.swing.JTextField();
        rolesBox = new javax.swing.JComboBox<>();
        imagenRol = new javax.swing.JLabel();
        fechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcionArea = new javax.swing.JTextArea();
        crear_usuario = new javax.swing.JButton();
        contraseña_field = new javax.swing.JPasswordField();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(164, 180, 101));

        bkgHeader.setBackground(new java.awt.Color(254, 250, 224));

        panelTitulo.setBackground(new java.awt.Color(255, 207, 80));

        etiTituloPrestamista.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N
        etiTituloPrestamista.setForeground(new java.awt.Color(98, 111, 71));
        etiTituloPrestamista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiTituloPrestamista.setText("Registro");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiTituloPrestamista, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiTituloPrestamista, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelVolver.setBackground(new java.awt.Color(255, 207, 80));

        imgVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver x24.png"))); // NOI18N
        imgVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgVolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelVolverLayout = new javax.swing.GroupLayout(panelVolver);
        panelVolver.setLayout(panelVolverLayout);
        panelVolverLayout.setHorizontalGroup(
            panelVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVolverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(imgVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelVolverLayout.setVerticalGroup(
            panelVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVolverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(imgVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout bkgHeaderLayout = new javax.swing.GroupLayout(bkgHeader);
        bkgHeader.setLayout(bkgHeaderLayout);
        bkgHeaderLayout.setHorizontalGroup(
            bkgHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkgHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        bkgHeaderLayout.setVerticalGroup(
            bkgHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkgHeaderLayout.createSequentialGroup()
                .addGroup(bkgHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bkgHeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bkgHeaderLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        nombre_field.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        nombre_field.setText("Nombre");
        nombre_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nombre_fieldMouseEntered(evt);
            }
        });
        nombre_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_fieldActionPerformed(evt);
            }
        });

        apellido_field.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        apellido_field.setText("Apellido");
        apellido_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellido_fieldActionPerformed(evt);
            }
        });

        documento_field.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        documento_field.setText("Documento");
        documento_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documento_fieldActionPerformed(evt);
            }
        });

        direccion_field.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        direccion_field.setText("Direccion");
        direccion_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccion_fieldActionPerformed(evt);
            }
        });

        rolesBox.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        rolesBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Roles", "Quiero prestar", "Quiero cobrar", "Quiero que me presten" }));
        rolesBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabel2.setText("Apellido");

        jLabel3.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabel3.setText("Documento");

        jLabel4.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabel4.setText("Direccion");

        jLabel5.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabel5.setText("Contraseña");

        jLabel6.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabel6.setText("Seleccione su fecha de nacimiento:");

        descripcionArea.setEditable(false);
        descripcionArea.setColumns(20);
        descripcionArea.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        descripcionArea.setRows(5);
        jScrollPane2.setViewportView(descripcionArea);

        crear_usuario.setText("¡Crear!");
        crear_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_usuarioActionPerformed(evt);
            }
        });

        contraseña_field.setText("Contraseña");

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkgHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombre_field)
                            .addComponent(apellido_field)
                            .addComponent(documento_field, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(direccion_field)
                            .addComponent(contraseña_field))
                        .addGap(18, 18, 18)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                                    .addComponent(fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(69, 69, 69)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                                .addComponent(crear_usuario)
                                .addGap(96, 96, 96))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imagenRol, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rolesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(bkgHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(apellido_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(documento_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccion_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crear_usuario)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseña_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(5, 5, 5)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(rolesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imagenRol, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void direccion_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccion_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccion_fieldActionPerformed

    private void documento_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documento_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_documento_fieldActionPerformed

    private void apellido_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellido_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellido_fieldActionPerformed

    private void nombre_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_fieldActionPerformed

    private void nombre_fieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombre_fieldMouseEntered
        // TODO add your handling code here:
        nombre_field.setText("");
    }//GEN-LAST:event_nombre_fieldMouseEntered

    private void imgVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgVolverMouseClicked
        Login abrir = new Login();
        abrir.setVisible(true);
        dispose();
    }//GEN-LAST:event_imgVolverMouseClicked

    private void crear_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_usuarioActionPerformed
        // TODO add your handling code here:
        ValidacionRegistro validacion = new ValidacionRegistro(
                nombre_field, apellido_field, documento_field,
                direccion_field, contraseña_field, fechaNacimiento
        );

        if (validacion.validarRegistro()) {
            CobradorHandler registrarCobrador = new CobradorHandler();
            registrarCobrador.registrarCobrador(documento_field.getText(), nombre_field.getText(), apellido_field.getText(), direccion_field.getText(), contraseña_field.getText(), fechaNacimiento.getDate());
        }
    }//GEN-LAST:event_crear_usuarioActionPerformed

    public class ValidacionRegistro {

        // Componentes del formulario (asumiendo que son campos de texto JTextField)
        private JTextField txtNombre;
        private JTextField txtApellido;
        private JTextField txtDocumento;
        private JTextField txtDireccion;
        private JPasswordField txtContraseña;
        private JDateChooser dateChooserFechaNacimiento;

        // Constructor que recibe los componentes
        public ValidacionRegistro(JTextField nombre, JTextField apellido, JTextField documento,
                JTextField direccion, JPasswordField contraseña, JDateChooser fechaNacimiento) {
            this.txtNombre = nombre;
            this.txtApellido = apellido;
            this.txtDocumento = documento;
            this.txtDireccion = direccion;
            this.txtContraseña = contraseña;
            this.dateChooserFechaNacimiento = fechaNacimiento;
        }

        /**
         * Valida todos los campos del formulario y la edad del usuario
         *
         * @return true si todos los campos son válidos y el usuario es mayor de
         * 18 años, false en caso contrario
         */
        public boolean validarRegistro() {
            // Validar campos vacíos
            if (txtNombre.getText().trim().isEmpty()
                    || txtApellido.getText().trim().isEmpty()
                    || txtDocumento.getText().trim().isEmpty()
                    || txtDireccion.getText().trim().isEmpty()
                    || txtContraseña.getPassword().length == 0) {

                JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }

            // Validar fecha de nacimiento
            if (dateChooserFechaNacimiento.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Debe seleccionar una fecha de nacimiento", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }

            // Calcular edad
            Date fechaNac = dateChooserFechaNacimiento.getDate();
            int edad = calcularEdad(fechaNac);

            if (edad < 18) {
                JOptionPane.showMessageDialog(null, "Debe ser mayor de 18 años para registrarse", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }

            // Si todo está correcto
            return true;
        }

        /**
         * Calcula la edad basada en la fecha de nacimiento
         *
         * @param fechaNacimiento Fecha de nacimiento del usuario
         * @return Edad calculada
         */
        private int calcularEdad(Date fechaNacimiento) {
            Calendar fechaNac = Calendar.getInstance();
            fechaNac.setTime(fechaNacimiento);

            Calendar fechaActual = Calendar.getInstance();

            int edad = fechaActual.get(Calendar.YEAR) - fechaNac.get(Calendar.YEAR);

            // Ajustar si aún no ha pasado el cumpleaños este año
            if (fechaActual.get(Calendar.MONTH) < fechaNac.get(Calendar.MONTH)) {
                edad--;
            } else if (fechaActual.get(Calendar.MONTH) == fechaNac.get(Calendar.MONTH)
                    && fechaActual.get(Calendar.DAY_OF_MONTH) < fechaNac.get(Calendar.DAY_OF_MONTH)) {
                edad--;
            }

            return edad;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crearUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JTextField apellido_field;
    private javax.swing.JPanel bkgHeader;
    private javax.swing.JPasswordField contraseña_field;
    private javax.swing.JButton crear_usuario;
    private javax.swing.JTextArea descripcionArea;
    private javax.swing.JTextField direccion_field;
    private javax.swing.JTextField documento_field;
    private javax.swing.JLabel etiTituloPrestamista;
    private com.toedter.calendar.JDateChooser fechaNacimiento;
    private javax.swing.JLabel imagenRol;
    private javax.swing.JLabel imgVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField nombre_field;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelVolver;
    private javax.swing.JComboBox<String> rolesBox;
    // End of variables declaration//GEN-END:variables
}
