/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author conta
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        imagenLogin = new javax.swing.JLabel();
        backForm = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        BackgraundImg = new javax.swing.JPanel();
        imgUsurio = new javax.swing.JLabel();
        btnIngesar = new javax.swing.JPanel();
        etiIngresar = new javax.swing.JLabel();
        etiCrearUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(164, 180, 101));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenLogin.setForeground(new java.awt.Color(98, 111, 71));
        imagenLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenLogin.setText("Imagen Login");
        imagenLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(98, 111, 71)));
        Background.add(imagenLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 410));

        backForm.setBackground(new java.awt.Color(254, 250, 224));
        backForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 207, 80), 5));

        txtUsuario.setBackground(new java.awt.Color(98, 111, 71));
        txtUsuario.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(254, 250, 224));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtUsuario.setText("USUARIO");
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        txtContraseña.setBackground(new java.awt.Color(98, 111, 71));
        txtContraseña.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(254, 250, 224));
        txtContraseña.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtContraseña.setText("Contraseña");
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });

        BackgraundImg.setBackground(new java.awt.Color(98, 111, 71));
        BackgraundImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 207, 80), 5));

        imgUsurio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgUsurio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario x64.png"))); // NOI18N

        javax.swing.GroupLayout BackgraundImgLayout = new javax.swing.GroupLayout(BackgraundImg);
        BackgraundImg.setLayout(BackgraundImgLayout);
        BackgraundImgLayout.setHorizontalGroup(
            BackgraundImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgraundImgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgUsurio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BackgraundImgLayout.setVerticalGroup(
            BackgraundImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgraundImgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgUsurio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnIngesar.setBackground(new java.awt.Color(255, 207, 80));

        etiIngresar.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        etiIngresar.setForeground(new java.awt.Color(254, 250, 224));
        etiIngresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiIngresar.setText("INGRESAR");

        javax.swing.GroupLayout btnIngesarLayout = new javax.swing.GroupLayout(btnIngesar);
        btnIngesar.setLayout(btnIngesarLayout);
        btnIngesarLayout.setHorizontalGroup(
            btnIngesarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnIngesarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnIngesarLayout.setVerticalGroup(
            btnIngesarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnIngesarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        etiCrearUsuario.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        etiCrearUsuario.setForeground(new java.awt.Color(98, 111, 71));
        etiCrearUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiCrearUsuario.setText("Crear nuevo usuario");

        javax.swing.GroupLayout backFormLayout = new javax.swing.GroupLayout(backForm);
        backForm.setLayout(backFormLayout);
        backFormLayout.setHorizontalGroup(
            backFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backFormLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(backFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BackgraundImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContraseña)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addGroup(backFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(etiCrearUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(btnIngesar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );
        backFormLayout.setVerticalGroup(
            backFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backFormLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(BackgraundImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIngesar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiCrearUsuario)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        Background.add(backForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 290, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgraundImg;
    private javax.swing.JPanel Background;
    private javax.swing.JPanel backForm;
    private javax.swing.JPanel btnIngesar;
    private javax.swing.JLabel etiCrearUsuario;
    private javax.swing.JLabel etiIngresar;
    private javax.swing.JLabel imagenLogin;
    private javax.swing.JLabel imgUsurio;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
