/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author conta
 */
public class Prestamista extends javax.swing.JFrame {

    /**
     * Creates new form Prestamista
     */
    public Prestamista() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        bkgHeader = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        etiTituloPrestamista = new javax.swing.JLabel();
        imgUsuario = new javax.swing.JLabel();
        panelVolver = new javax.swing.JPanel();
        imgVolver = new javax.swing.JLabel();
        bkgCuerpo = new javax.swing.JPanel();
        barraPrestamos = new javax.swing.JPanel();
        panelPrestamos = new javax.swing.JPanel();
        etiPrestamos = new javax.swing.JLabel();
        prestamista_prestamo1 = new javax.swing.JPanel();
        etiPrestamo_p1 = new javax.swing.JLabel();
        prestamista_prestamo2 = new javax.swing.JPanel();
        etiPrestamo_p2 = new javax.swing.JLabel();
        prestamista_prestamo3 = new javax.swing.JPanel();
        etiPrestamo_p3 = new javax.swing.JLabel();
        prestamista_prestamo4 = new javax.swing.JPanel();
        etiPrestamo_p4 = new javax.swing.JLabel();
        prestamista_prestamo5 = new javax.swing.JPanel();
        etiPrestamo_p5 = new javax.swing.JLabel();
        panelBackgroundDescripcion = new javax.swing.JPanel();
        etiNombreDeuAsig = new javax.swing.JLabel();
        panelDescripcion = new javax.swing.JPanel();
        etiTutuloDescripcion = new javax.swing.JLabel();
        etiDescripcionPrestamo = new javax.swing.JLabel();
        panelTotalPrestamo = new javax.swing.JPanel();
        etiValorTotalPrestamo = new javax.swing.JLabel();
        etiTotalDeprestamo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(164, 180, 101));

        bkgHeader.setBackground(new java.awt.Color(254, 250, 224));

        panelTitulo.setBackground(new java.awt.Color(255, 207, 80));

        etiTituloPrestamista.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N
        etiTituloPrestamista.setForeground(new java.awt.Color(98, 111, 71));
        etiTituloPrestamista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiTituloPrestamista.setText("Prestamista");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiTituloPrestamista, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiTituloPrestamista, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        imgUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario x100.png"))); // NOI18N

        panelVolver.setBackground(new java.awt.Color(255, 207, 80));

        imgVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver x24.png"))); // NOI18N
        imgVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgVolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelVolverLayout = new javax.swing.GroupLayout(panelVolver);
        panelVolver.setLayout(panelVolverLayout);
        panelVolverLayout.setHorizontalGroup(
            panelVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVolverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(imgVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelVolverLayout.setVerticalGroup(
            panelVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVolverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(imgVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout bkgHeaderLayout = new javax.swing.GroupLayout(bkgHeader);
        bkgHeader.setLayout(bkgHeaderLayout);
        bkgHeaderLayout.setHorizontalGroup(
            bkgHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkgHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(imgUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        bkgHeaderLayout.setVerticalGroup(
            bkgHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkgHeaderLayout.createSequentialGroup()
                .addGroup(bkgHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bkgHeaderLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bkgHeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(bkgHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bkgCuerpo.setBackground(new java.awt.Color(98, 111, 71));

        barraPrestamos.setBackground(new java.awt.Color(254, 250, 224));

        panelPrestamos.setBackground(new java.awt.Color(164, 180, 101));

        etiPrestamos.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        etiPrestamos.setForeground(new java.awt.Color(254, 250, 224));
        etiPrestamos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPrestamos.setText("PRESTAMOS");

        javax.swing.GroupLayout panelPrestamosLayout = new javax.swing.GroupLayout(panelPrestamos);
        panelPrestamos.setLayout(panelPrestamosLayout);
        panelPrestamosLayout.setHorizontalGroup(
            panelPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelPrestamosLayout.setVerticalGroup(
            panelPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        prestamista_prestamo1.setBackground(new java.awt.Color(255, 207, 80));

        etiPrestamo_p1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        etiPrestamo_p1.setForeground(new java.awt.Color(98, 111, 71));
        etiPrestamo_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPrestamo_p1.setText("Prestamo 1");

        javax.swing.GroupLayout prestamista_prestamo1Layout = new javax.swing.GroupLayout(prestamista_prestamo1);
        prestamista_prestamo1.setLayout(prestamista_prestamo1Layout);
        prestamista_prestamo1Layout.setHorizontalGroup(
            prestamista_prestamo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prestamista_prestamo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamo_p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        prestamista_prestamo1Layout.setVerticalGroup(
            prestamista_prestamo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prestamista_prestamo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamo_p1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        prestamista_prestamo2.setBackground(new java.awt.Color(255, 207, 80));

        etiPrestamo_p2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        etiPrestamo_p2.setForeground(new java.awt.Color(98, 111, 71));
        etiPrestamo_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPrestamo_p2.setText("Prestamo 2");

        javax.swing.GroupLayout prestamista_prestamo2Layout = new javax.swing.GroupLayout(prestamista_prestamo2);
        prestamista_prestamo2.setLayout(prestamista_prestamo2Layout);
        prestamista_prestamo2Layout.setHorizontalGroup(
            prestamista_prestamo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prestamista_prestamo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamo_p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        prestamista_prestamo2Layout.setVerticalGroup(
            prestamista_prestamo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prestamista_prestamo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamo_p2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        prestamista_prestamo3.setBackground(new java.awt.Color(255, 207, 80));

        etiPrestamo_p3.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        etiPrestamo_p3.setForeground(new java.awt.Color(98, 111, 71));
        etiPrestamo_p3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPrestamo_p3.setText("Prestamo 3");

        javax.swing.GroupLayout prestamista_prestamo3Layout = new javax.swing.GroupLayout(prestamista_prestamo3);
        prestamista_prestamo3.setLayout(prestamista_prestamo3Layout);
        prestamista_prestamo3Layout.setHorizontalGroup(
            prestamista_prestamo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prestamista_prestamo3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamo_p3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        prestamista_prestamo3Layout.setVerticalGroup(
            prestamista_prestamo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prestamista_prestamo3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamo_p3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        prestamista_prestamo4.setBackground(new java.awt.Color(255, 207, 80));

        etiPrestamo_p4.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        etiPrestamo_p4.setForeground(new java.awt.Color(98, 111, 71));
        etiPrestamo_p4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPrestamo_p4.setText("Prestamo 4");

        javax.swing.GroupLayout prestamista_prestamo4Layout = new javax.swing.GroupLayout(prestamista_prestamo4);
        prestamista_prestamo4.setLayout(prestamista_prestamo4Layout);
        prestamista_prestamo4Layout.setHorizontalGroup(
            prestamista_prestamo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prestamista_prestamo4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamo_p4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        prestamista_prestamo4Layout.setVerticalGroup(
            prestamista_prestamo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prestamista_prestamo4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamo_p4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        prestamista_prestamo5.setBackground(new java.awt.Color(255, 207, 80));

        etiPrestamo_p5.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        etiPrestamo_p5.setForeground(new java.awt.Color(98, 111, 71));
        etiPrestamo_p5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPrestamo_p5.setText("Prestamo 5");

        javax.swing.GroupLayout prestamista_prestamo5Layout = new javax.swing.GroupLayout(prestamista_prestamo5);
        prestamista_prestamo5.setLayout(prestamista_prestamo5Layout);
        prestamista_prestamo5Layout.setHorizontalGroup(
            prestamista_prestamo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prestamista_prestamo5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamo_p5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        prestamista_prestamo5Layout.setVerticalGroup(
            prestamista_prestamo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prestamista_prestamo5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiPrestamo_p5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout barraPrestamosLayout = new javax.swing.GroupLayout(barraPrestamos);
        barraPrestamos.setLayout(barraPrestamosLayout);
        barraPrestamosLayout.setHorizontalGroup(
            barraPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barraPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prestamista_prestamo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prestamista_prestamo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prestamista_prestamo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prestamista_prestamo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prestamista_prestamo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        barraPrestamosLayout.setVerticalGroup(
            barraPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(prestamista_prestamo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prestamista_prestamo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prestamista_prestamo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prestamista_prestamo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prestamista_prestamo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBackgroundDescripcion.setBackground(new java.awt.Color(254, 250, 224));

        etiNombreDeuAsig.setForeground(new java.awt.Color(98, 111, 71));
        etiNombreDeuAsig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiNombreDeuAsig.setText("Nombre del deudor");
        etiNombreDeuAsig.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(98, 111, 71), 3));

        panelDescripcion.setBackground(new java.awt.Color(254, 250, 224));
        panelDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(98, 111, 71), 3));

        etiTutuloDescripcion.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        etiTutuloDescripcion.setForeground(new java.awt.Color(98, 111, 71));
        etiTutuloDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiTutuloDescripcion.setText("DESCRIPCION");

        etiDescripcionPrestamo.setForeground(new java.awt.Color(98, 111, 71));
        etiDescripcionPrestamo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiDescripcionPrestamo.setText("descripcion del prestamo ");
        etiDescripcionPrestamo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(98, 111, 71)));

        javax.swing.GroupLayout panelDescripcionLayout = new javax.swing.GroupLayout(panelDescripcion);
        panelDescripcion.setLayout(panelDescripcionLayout);
        panelDescripcionLayout.setHorizontalGroup(
            panelDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiTutuloDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiDescripcionPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        panelDescripcionLayout.setVerticalGroup(
            panelDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiTutuloDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiDescripcionPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        panelTotalPrestamo.setBackground(new java.awt.Color(164, 180, 101));

        etiValorTotalPrestamo.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        etiValorTotalPrestamo.setForeground(new java.awt.Color(98, 111, 71));
        etiValorTotalPrestamo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiValorTotalPrestamo.setText("1.000.000");

        javax.swing.GroupLayout panelTotalPrestamoLayout = new javax.swing.GroupLayout(panelTotalPrestamo);
        panelTotalPrestamo.setLayout(panelTotalPrestamoLayout);
        panelTotalPrestamoLayout.setHorizontalGroup(
            panelTotalPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiValorTotalPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTotalPrestamoLayout.setVerticalGroup(
            panelTotalPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiValorTotalPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        etiTotalDeprestamo.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 10)); // NOI18N
        etiTotalDeprestamo.setForeground(new java.awt.Color(98, 111, 71));
        etiTotalDeprestamo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiTotalDeprestamo.setText("Total de prestamo");

        javax.swing.GroupLayout panelBackgroundDescripcionLayout = new javax.swing.GroupLayout(panelBackgroundDescripcion);
        panelBackgroundDescripcion.setLayout(panelBackgroundDescripcionLayout);
        panelBackgroundDescripcionLayout.setHorizontalGroup(
            panelBackgroundDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundDescripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBackgroundDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackgroundDescripcionLayout.createSequentialGroup()
                        .addComponent(panelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelBackgroundDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelTotalPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etiTotalDeprestamo, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                    .addComponent(etiNombreDeuAsig, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        panelBackgroundDescripcionLayout.setVerticalGroup(
            panelBackgroundDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundDescripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBackgroundDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBackgroundDescripcionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(etiTotalDeprestamo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTotalPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBackgroundDescripcionLayout.createSequentialGroup()
                        .addComponent(etiNombreDeuAsig, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout bkgCuerpoLayout = new javax.swing.GroupLayout(bkgCuerpo);
        bkgCuerpo.setLayout(bkgCuerpoLayout);
        bkgCuerpoLayout.setHorizontalGroup(
            bkgCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkgCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barraPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelBackgroundDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bkgCuerpoLayout.setVerticalGroup(
            bkgCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkgCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barraPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(bkgCuerpoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(panelBackgroundDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bkgCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bkgHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bkgHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bkgCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgVolverMouseClicked
        Login abrir = new Login();
        abrir.setVisible(true);
        dispose();
    }//GEN-LAST:event_imgVolverMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestamista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestamista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestamista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestamista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prestamista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel barraPrestamos;
    private javax.swing.JPanel bkgCuerpo;
    private javax.swing.JPanel bkgHeader;
    private javax.swing.JLabel etiDescripcionPrestamo;
    private javax.swing.JLabel etiNombreDeuAsig;
    private javax.swing.JLabel etiPrestamo_p1;
    private javax.swing.JLabel etiPrestamo_p2;
    private javax.swing.JLabel etiPrestamo_p3;
    private javax.swing.JLabel etiPrestamo_p4;
    private javax.swing.JLabel etiPrestamo_p5;
    private javax.swing.JLabel etiPrestamos;
    private javax.swing.JLabel etiTituloPrestamista;
    private javax.swing.JLabel etiTotalDeprestamo;
    private javax.swing.JLabel etiTutuloDescripcion;
    private javax.swing.JLabel etiValorTotalPrestamo;
    private javax.swing.JLabel imgUsuario;
    private javax.swing.JLabel imgVolver;
    private javax.swing.JPanel panelBackgroundDescripcion;
    private javax.swing.JPanel panelDescripcion;
    private javax.swing.JPanel panelPrestamos;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelTotalPrestamo;
    private javax.swing.JPanel panelVolver;
    private javax.swing.JPanel prestamista_prestamo1;
    private javax.swing.JPanel prestamista_prestamo2;
    private javax.swing.JPanel prestamista_prestamo3;
    private javax.swing.JPanel prestamista_prestamo4;
    private javax.swing.JPanel prestamista_prestamo5;
    // End of variables declaration//GEN-END:variables
}
